### ISSUE TITLE
How to add login account ?

### ISSUE THREAD

**Issue by kesz24** [foxovsky/PointBlank#1]
because i try to login with admin admin it wont enter
i try to fill the id at the account database it wont enter too
i even try sha1 and md5 nothing work

**Comment by foxovsky** [comment]
Hey

Use registration from site(/web/)

Also I will soon upload the updated build

**Comment by kesz24** [comment]
ok thanks

**Comment by foxovsky** [comment]
i'm updated repository, fix registration(site) and killmarks(core)

**Comment by kesz24** [comment]
ok i see 
it works 
and i found something about the auth server
it force closed when i success login

**Comment by foxovsky** [comment]
change status account to 1 in database, accounts
