### ISSUE TITLE
Client ?

### ISSUE THREAD

**Issue by SkelletonX** [foxovsky/PointBlank#11]
Where can I download the correct version of the client(game) ?

**Comment by foxovsky** [comment]
Brazil 2015 Client

http://forum.ragezone.com/f904/client-pb-br-opcode-1106453/

**Comment by SkelletonX** [comment]
I will have to upgrade the server to get the current client packet (2017)

**Comment by foxovsky** [comment]
can create a separate branch?

**Comment by SkelletonX** [comment]
Yes :)
